export const API_RELATIONS_FETCH_START = 'API_RELATIONS_FETCH_START';
export const API_RELATIONS_FETCH_SUCCESS = 'API_RELATIONS_FETCH_SUCCESS';
export const API_RELATIONS_FETCH_ERROR = 'API_RELATIONS_FETCH_ERROR';

export type ApiRelationsActionType = 'API_RELATIONS_FETCH_START' | 'API_RELATIONS_FETCH_SUCCESS' | 'API_RELATIONS_FETCH_ERROR';
