export const API_DATABASE_FETCH_START = 'API_DATABASE_FETCH_START';
export const API_DATABASE_FETCH_SUCCESS = 'API_DATABASE_FETCH_SUCCESS';
export const API_DATABASE_FETCH_ERROR = 'API_DATABASE_FETCH_ERROR';

export const API_DATABASE_CHOOSE = 'API_DATABASE_CHOOSE';

export type ApiDatabaseActionType = 'API_DATABASE_FETCH_START' | 'API_DATABASE_FETCH_SUCCESS' | 'API_DATABASE_FETCH_ERROR' | 'API_DATABASE_CHOOSE';
