export const API_ADD_SOURCE_FETCH_START = 'API_ADD_SOURCE_FETCH_START';
export const API_ADD_SOURCE_FETCH_SUCCESS = 'API_ADD_SOURCE_FETCH_SUCCESS';
export const API_ADD_SOURCE_FETCH_ERROR = 'API_ADD_SOURCE_FETCH_ERROR';

export type ApiAddSourceActionType = 'API_ADD_SOURCE_FETCH_START' | 'API_ADD_SOURCE_FETCH_START' | 'API_ADD_SOURCE_FETCH_START';
