export const API_ENTITIES_FETCH_START = 'API_ENTITIES_FETCH_START';
export const API_ENTITIES_FETCH_SUCCESS = 'API_ENTITIES_FETCH_SUCCESS';
export const API_ENTITIES_FETCH_ERROR = 'API_ENTITIES_FETCH_ERROR';

export const API_ENTITIES_CLEAR = 'API_ENTITIES_CLEAR';

export type ApiEntitiesActionType = 'API_ENTITIES_FETCH_START' | 'API_ENTITIES_FETCH_SUCCESS' | 'API_ENTITIES_FETCH_ERROR' | 'API_ENTITIES_CLEAR';
