export const DRAG_FIELD_IN_ENTITY = 'DRAG_FIELD_IN_ENTITY';
export const DRAG_FIELD_BETWEEN_ENTITIES = 'DRAG_FIELD_BETWEEN_ENTITIES';

export const DRAG_FIELD_FROM_ENTITY_TO_SIDEBAR = 'DRAG_FIELD_FROM_ENTITY_TO_SIDEBAR';

export const DRAG_FIELD_FROM_ENTITY_TO_WORKSPACE = 'DRAG_FIELD_FROM_ENTITY_TO_WORKSPACE';
export const DRAG_FIELD_FROM_WORKSPACE_TO_ENTITY = 'DRAG_FIELD_FROM_WORKSPACE_TO_ENTITY';

export type DragFieldsActionType = 'DRAG_FIELD_IN_ENTITY' | 'DRAG_FIELD_BETWEEN_ENTITIES' | 'DRAG_FIELD_FROM_ENTITY_TO_SIDEBAR' | 'DRAG_FIELD_FROM_ENTITY_TO_WORKSPACE' | 'DRAG_FIELD_FROM_WORKSPACE_TO_ENTITY';
