export const API_FIELDS_FETCH_START = 'API_FIELDS_FETCH_START';
export const API_FIELDS_FETCH_SUCCESS = 'API_FIELDS_FETCH_SUCCESS';
export const API_FIELDS_FETCH_ERROR = 'API_FIELDS_FETCH_ERROR';

export type ApiFieldsActionType = 'API_FIELDS_FETCH_START' | 'API_FIELDS_FETCH_SUCCESS' | 'API_FIELDS_FETCH_ERROR';
