export const MODAL_CONFIG_OPEN = 'MODAL_CONFIG_OPEN';
export const MODAL_CONFIG_CLOSE = 'MODAL_CONFIG_CLOSE';

export const MODAL_MAIN_OPEN = 'MODAL_MAIN_OPEN';
export const MODAL_MAIN_CLOSE = 'MODAL_MAIN_CLOSE';

export const MODAL_NEWDB_OPEN = 'MODAL_NEWDB_OPEN';
export const MODAL_NEWDB_CLOSE = 'MODAL_NEWDB_CLOSE';

export type ModalActionType = 'MODAL_CONFIG_OPEN' | 'MODAL_CONFIG_CLOSE' | 'MODAL_MAIN_OPEN' | 'MODAL_MAIN_CLOSE' | 'MODAL_NEWDB_OPEN' | 'MODAL_NEWDB_CLOSE';

export const FIELD_TOGGLE = 'FIELD_TOGGLE';
export const FIELD_SET_OPERATION = 'FIELD_SET_OPERATION';
export const FIELD_CLEAR_OPERATION = 'FIELD_CLEAR_OPERATION';
export const FIELD_SET_VALUE = 'FIELD_SET_VALUE';

export type FieldActionType = 'FIELD_TOGGLE' | 'FIELD_SET_OPERATION' | 'FIELD_CLEAR_OPERATION' | 'FIELD_SET_VALUE';
