export const API_RESPONSE_FETCH_START = 'API_RESPONSE_FETCH_START';
export const API_RESPONSE_FETCH_SUCCESS = 'API_RESPONSE_FETCH_SUCCESS';
export const API_RESPONSE_FETCH_ERROR = 'API_RESPONSE_FETCH_ERROR';

export type ApiResponseActionType = 'API_RESPONSE_FETCH_START' | 'API_RESPONSE_FETCH_START' | 'API_RESPONSE_FETCH_START';
